# Generated by Django 4.1.7 on 2023-04-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mattress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=511)),
                ('description', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('start_height', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('end_height', models.DecimalField(decimal_places=1, default=300, max_digits=4)),
                ('start_weight', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('end_weight', models.DecimalField(decimal_places=1, default=300, max_digits=4)),
            ],
        ),
    ]
