# Generated by Django 4.1.7 on 2023-04-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Askona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mattress',
            old_name='end_height',
            new_name='max_height',
        ),
        migrations.RenameField(
            model_name='mattress',
            old_name='end_weight',
            new_name='max_weight',
        ),
        migrations.RenameField(
            model_name='mattress',
            old_name='start_height',
            new_name='min_height',
        ),
        migrations.RenameField(
            model_name='mattress',
            old_name='start_weight',
            new_name='min_weight',
        ),
    ]
