# Generated by Django 4.1.7 on 2023-04-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Askona', '0002_rename_end_height_mattress_max_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattress',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
